### ISSUE TITLE
Chat panel

### ISSUE THREAD

**Issue by abhishekmedipta** [facebook/taste-tester#50]
There is a bug in facebook in chat, there is a chat panel in right side of facebook page, when there are lots of people are online and that time, if we scroll the scroll bar, then last user are not showing properly.

see the attachment..

![screenshot 100](https://cloud.githubusercontent.com/assets/16331239/14066459/2e31824e-f467-11e5-8a0a-870ab3981411.png)
![screenshot 100 _3](https://cloud.githubusercontent.com/assets/16331239/14066460/2e5664ba-f467-11e5-82ec-d54ca3b8ccdb.png)

**Comment by jaymzh** [comment]
This github repository is for taste-tester only. Please file facebook bugs via the Facebook helpsite.

**Comment by abhishekmedipta** [comment]
@jaymzh  Can u please tell where i can report this issue, please tell me right repository.

**Comment by jaymzh** [comment]
https://www.facebook.com/help
