### ISSUE TITLE
auto generated knife config file should include hostname

### ISSUE THREAD

**Issue by joshuamiller01** [facebook/taste-tester#57]
taste-tester will build a knife config file to point at the local chef-zero instance in ~/.chef/ .  If multiple instances of taste-tester are invoked and the home directories are on shared storage you can have conflicts.   Possible easy fix is to change the config file name to include the local hostname (considering it's already writing that into said file anyways).

**Comment by jaymzh** [comment]
#83  will allow you to put this in a local directory that works for you.
