### ISSUE TITLE
tt assumes all machines are in the same timezone

### ISSUE THREAD

**Issue by jaymzh** [facebook/taste-tester#62]
TT calculates what the test-timestamp should be on the local machine and then passes the result through to the remote machine in a literal format.

If the remote machine is in a timezone more than an hour ahead, then the host will immediately be un-taste-tested.

**Comment by jaymzh** [comment]
@odcinek  didn't you do this?

**Comment by odcinek** [comment]
@jaymzh I did, in #64.
